// SPDX-License-Identifier: ice License 1.0

export const Images = {
  tabbar: {
    itemBackground: require('./tabbar/item-background.png'),
    miningBackground: require('./tabbar/mining-background.png'),
  },
  roles: {
    ambassador: require('./roles/ambassador.png'),
    // TODO: Add actual image once needed
    ambassadorInactive: require('./roles/pioneer-inactive.png'),
    snowman: require('./roles/pioneer.png'),
    snowmanInactive: require('./roles/pioneer-inactive.png'),
  },
  badges: {
    social0_achieved_true: require('./badges/social0_achieved_true.png'),
    social1_achieved_true: require('./badges/social1_achieved_true.png'),
    social2_achieved_true: require('./badges/social2_achieved_true.png'),
    social3_achieved_true: require('./badges/social3_achieved_true.png'),
    social4_achieved_true: require('./badges/social4_achieved_true.png'),
    social5_achieved_true: require('./badges/social5_achieved_true.png'),
    social6_achieved_true: require('./badges/social6_achieved_true.png'),
    social7_achieved_true: require('./badges/social7_achieved_true.png'),
    social8_achieved_true: require('./badges/social8_achieved_true.png'),
    social9_achieved_true: require('./badges/social9_achieved_true.png'),
    social0_achieved_false: require('./badges/social0_achieved_false.png'),
    social1_achieved_false: require('./badges/social1_achieved_false.png'),
    social2_achieved_false: require('./badges/social2_achieved_false.png'),
    social3_achieved_false: require('./badges/social3_achieved_false.png'),
    social4_achieved_false: require('./badges/social4_achieved_false.png'),
    social5_achieved_false: require('./badges/social5_achieved_false.png'),
    social6_achieved_false: require('./badges/social6_achieved_false.png'),
    social7_achieved_false: require('./badges/social7_achieved_false.png'),
    social8_achieved_false: require('./badges/social8_achieved_false.png'),
    social9_achieved_false: require('./badges/social9_achieved_false.png'),
    coin0_achieved_true: require('./badges/coin0_achieved_true.png'),
    coin1_achieved_true: require('./badges/coin1_achieved_true.png'),
    coin2_achieved_true: require('./badges/coin2_achieved_true.png'),
    coin3_achieved_true: require('./badges/coin3_achieved_true.png'),
    coin4_achieved_true: require('./badges/coin4_achieved_true.png'),
    coin5_achieved_true: require('./badges/coin5_achieved_true.png'),
    coin6_achieved_true: require('./badges/coin6_achieved_true.png'),
    coin7_achieved_true: require('./badges/coin7_achieved_true.png'),
    coin8_achieved_true: require('./badges/coin8_achieved_true.png'),
    coin9_achieved_true: require('./badges/coin9_achieved_true.png'),
    coin0_achieved_false: require('./badges/coin0_achieved_false.png'),
    coin1_achieved_false: require('./badges/coin1_achieved_false.png'),
    coin2_achieved_false: require('./badges/coin2_achieved_false.png'),
    coin3_achieved_false: require('./badges/coin3_achieved_false.png'),
    coin4_achieved_false: require('./badges/coin4_achieved_false.png'),
    coin5_achieved_false: require('./badges/coin5_achieved_false.png'),
    coin6_achieved_false: require('./badges/coin6_achieved_false.png'),
    coin7_achieved_false: require('./badges/coin7_achieved_false.png'),
    coin8_achieved_false: require('./badges/coin8_achieved_false.png'),
    coin9_achieved_false: require('./badges/coin9_achieved_false.png'),
    level0_achieved_true: require('./badges/level0_achieved_true.png'),
    level1_achieved_true: require('./badges/level1_achieved_true.png'),
    level2_achieved_true: require('./badges/level2_achieved_true.png'),
    level3_achieved_true: require('./badges/level3_achieved_true.png'),
    level4_achieved_true: require('./badges/level4_achieved_true.png'),
    level5_achieved_true: require('./badges/level5_achieved_true.png'),
    level0_achieved_false: require('./badges/level0_achieved_false.png'),
    level1_achieved_false: require('./badges/level1_achieved_false.png'),
    level2_achieved_false: require('./badges/level2_achieved_false.png'),
    level3_achieved_false: require('./badges/level3_achieved_false.png'),
    level4_achieved_false: require('./badges/level4_achieved_false.png'),
    level5_achieved_false: require('./badges/level5_achieved_false.png'),
  },
  phone: {
    confirmPhoneNumber: require('./phone/confirmPhoneNumber.png'),
    modifyPhoneNumber: require('./phone/modifyPhoneNumber.png'),
  },
  backgrounds: {
    linesBg: require('./backgrounds/linesBg.png'),
    privacyBgTop: require('./backgrounds/privacyBgTop.png'),
    privacyBgMiddle: require('./backgrounds/privacyBgMiddle.png'),
    privacyBgBottom: require('./backgrounds/privacyBgBottom.png'),
    linesHeaderBg: require('./backgrounds/linesHeaderBg.png'),
    adoptionCardBg: require('./backgrounds/adoptionCardBg.png'),
    levelCardBg: require('./backgrounds/levelCardBg.png'),
    referralsCardBg: require('./backgrounds/referralsCardBg.png'),
    walkthroughBg: require('./backgrounds/walkthrough.png'),
  },
  popUp: {
    updateRequired: require('./popup/please_update.png'),
    error: require('./popup/oops.png'),
    upToDate: require('./popup/already_updated.png'),
    resurrection: require('./popup/resurrection.png'),
    telegram: require('./popup/telegram.png'),
    earlyAccess: require('./popup/earlyAccess.png'),
  },
} as const;
