// SPDX-License-Identifier: ice License 1.0

export const Images = {
  tabbar: {
    itemBackground: require('./tabbar/item-background.png'),
    miningBackground: require('./tabbar/mining-background.png'),
  },
  roles: {
    ambassador: require('./roles/ambassador.png'),
    ambassadorInactive: require('./roles/pioneer-inactive.png'),
    snowman: require('./roles/pioneer.png'),
    snowmanInactive: require('./roles/pioneer-inactive.png'),
  },
  badges: {
    social0_achieved_true: require('./badges/social0_achieved_true.png'),
    social1_achieved_true: require('./badges/social1_achieved_true.png'),
    social2_achieved_true: require('./badges/social2_achieved_true.png'),
    social3_achieved_true: require('./badges/social3_achieved_true.png'),
    social4_achieved_true: require('./badges/social4_achieved_true.png'),
    social5_achieved_true: require('./badges/social5_achieved_true.png'),
    social6_achieved_true: require('./badges/social6_achieved_true.png'),
    social7_achieved_true: require('./badges/social7_achieved_true.png'),
    social8_achieved_true: require('./badges/social8_achieved_true.png'),
    social9_achieved_true: require('./badges/social9_achieved_true.png'),
    social0_achieved_false: require('./badges/social0_achieved_false.png'),
    social1_achieved_false: require('./badges/social1_achieved_false.png'),
    social2_achieved_false: require('./badges/social2_achieved_false.png'),
    social3_achieved_false: require('./badges/social3_achieved_false.png'),
    social4_achieved_false: require('./badges/social4_achieved_false.png'),
    social5_achieved_false: require('./badges/social5_achieved_false.png'),
    social6_achieved_false: require('./badges/social6_achieved_false.png'),
    social7_achieved_false: require('./badges/social7_achieved_false.png'),
    social8_achieved_false: require('./badges/social8_achieved_false.png'),
    social9_achieved_false: require('./badges/social9_achieved_false.png'),
    coin0_achieved_true: require('./badges/coin0_achieved_true.png'),
    coin1_achieved_true: require('./badges/coin1_achieved_true.png'),
    coin2_achieved_true: require('./badges/coin2_achieved_true.png'),
    coin3_achieved_true: require('./badges/coin3_achieved_true.png'),
    coin4_achieved_true: require('./badges/coin4_achieved_true.png'),
    coin5_achieved_true: require('./badges/coin5_achieved_true.png'),
    coin6_achieved_true: require('./badges/coin6_achieved_true.png'),
    coin7_achieved_true: require('./badges/coin7_achieved_true.png'),
    coin8_achieved_true: require('./badges/coin8_achieved_true.png'),
    coin9_achieved_true: require('./badges/coin9_achieved_true.png'),
    coin0_achieved_false: require('./badges/coin0_achieved_false.png'),
    coin1_achieved_false: require('./badges/coin1_achieved_false.png'),
    coin2_achieved_false: require('./badges/coin2_achieved_false.png'),
    coin3_achieved_false: require('./badges/coin3_achieved_false.png'),
    coin4_achieved_false: require('./badges/coin4_achieved_false.png'),
    coin5_achieved_false: require('./badges/coin5_achieved_false.png'),
    coin6_achieved_false: require('./badges/coin6_achieved_false.png'),
    coin7_achieved_false: require('./badges/coin7_achieved_false.png'),
    coin8_achieved_false: require('./badges/coin8_achieved_false.png'),
    coin9_achieved_false: require('./badges/coin9_achieved_false.png'),
    level0_achieved_true: require('./badges/level0_achieved_true.png'),
    level1_achieved_true: require('./badges/level1_achieved_true.png'),
    level2_achieved_true: require('./badges/level2_achieved_true.png'),
    level3_achieved_true: require('./badges/level3_achieved_true.png'),
    level4_achieved_true: require('./badges/level4_achieved_true.png'),
    level5_achieved_true: require('./badges/level5_achieved_true.png'),
    level0_achieved_false: require('./badges/level0_achieved_false.png'),
    level1_achieved_false: require('./badges/level1_achieved_false.png'),
    level2_achieved_false: require('./badges/level2_achieved_false.png'),
    level3_achieved_false: require('./badges/level3_achieved_false.png'),
    level4_achieved_false: require('./badges/level4_achieved_false.png'),
    level5_achieved_false: require('./badges/level5_achieved_false.png'),
    placeholder0: require('./badges/placeholder0.png'),
    placeholder1: require('./badges/placeholder1.png'),
    placeholder2: require('./badges/placeholder2.png'),
    faceAuth: require('./badges/face_auth.png'),
    cameraPermission: require('./badges/camera_permission.png'),
    socialKyc: {
      start: require('./badges/social_kyc/start.png'),
      success: require('./badges/social_kyc/success.png'),
      failure: require('./badges/social_kyc/failure.png'),
      fbDark: require('./social/social_kyc/fb_dark.png'),
      fbLight: require('./social/social_kyc/fb_light.png'),
      xDark: require('./social/social_kyc/x_dark.png'),
      xLight: require('./social/social_kyc/x_light.png'),
    },
  },
  phone: {
    confirmPhoneNumber: require('./phone/confirmPhoneNumber.png'),
    modifyPhoneNumber: require('./phone/modifyPhoneNumber.png'),
    phonePosition: require('./phone/phonePosition.png'),
  },
  backgrounds: {
    linesBg: require('./backgrounds/linesBg.png'),
    privacyBgTop: require('./backgrounds/privacyBgTop.png'),
    privacyBgMiddle: require('./backgrounds/privacyBgMiddle.png'),
    privacyBgBottom: require('./backgrounds/privacyBgBottom.png'),
    linesHeaderBg: require('./backgrounds/linesHeaderBg.png'),
    adoptionCardBg: require('./backgrounds/adoptionCardBg.png'),
    levelCardBg: require('./backgrounds/levelCardBg.png'),
    referralsCardBg: require('./backgrounds/referralsCardBg.png'),
    walkthroughBg: require('./backgrounds/walkthrough.png'),
    darkListItem: require('./backgrounds/darkListItem.png'),
    blueSquaresBg: require('./backgrounds/blueSquaresBg.png'),
  },
  popUp: {
    updateRequired: require('./popup/please_update.png'),
    error: require('./popup/oops.png'),
    upToDate: require('./popup/already_updated.png'),
    resurrection: require('./popup/resurrection.png'),
    linkEmail: require('./popup/link_email.png'),
    registrationUpdate: require('./popup/registration_update.png'),
    linked: require('./popup/linked.png'),
  },
  share: {
    telegram: require('./share/telegram.png'),
    twitter: require('./share/twitter.png'),
    whatsApp: require('./share/whatsApp.png'),
    email: require('./share/email.png'),
    facebook: require('./share/facebook.png'),
    link: require('./share/link.png'),
    more: require('./share/more.png'),
    sms: require('./share/sms.png'),
    shareProviders: require('./share/share_providers.png'),
    shareProviders2: require('./share/share_providers2.png'),
  },
  social: {
    tiktok: require('./social/tiktok.png'),
    youtube: require('./social/youtube.png'),
    linkedin: require('./social/linkedin.png'),
    facebook: require('./social/facebook.png'),
    instagram: require('./social/instagram.png'),
    telegram: require('./social/telegram.png'),
    reddit: require('./social/reddit.png'),
    // discord: require('./social/discord.png'),
    twitter: require('./social/twitter.png'),
    icons: {
      facebook: require('./social/icons/facebook.png'),
      github: require('./social/icons/github.png'),
      instagram: require('./social/icons/instagram.png'),
      linkedin: require('./social/icons/linkedin.png'),
      telegram: require('./social/icons/telegram.png'),
      tiktok: require('./social/icons/tiktok.png'),
      twitter: require('./social/icons/twitter.png'),
      youtube: require('./social/icons/youtube.png'),
      reddit: require('./social/icons/reddit.png'),
      // discord: require('./social/icons/discord.png'),
    },
  },
  creativeLibrary: {
    getStarted: require('./creative_library/get_started.png'),
    getStartedCarousel: {
      '01': require('./creative_library/get_started_carousel/01.png'),
      '02': require('./creative_library/get_started_carousel/02.png'),
      '03': require('./creative_library/get_started_carousel/03.png'),
      join: require('./creative_library/get_started_carousel/join.png'),
      invite: require('./creative_library/get_started_carousel/invite.png'),
      earn: require('./creative_library/get_started_carousel/earn.png'),
    },
    carousel: {
      iceBackground: require('./creative_library/carousel/ice_background.png'),
      ellipseBackground: require('./creative_library/carousel/ellipse_background.png'),
      videosIcon: require('./creative_library/carousel/videos_icon.png'),
      imagesIcon: require('./creative_library/carousel/images_icon.png'),
      browserIcon: require('./creative_library/carousel/browser_icon.png'),
    },
    socialSection: {
      blogs: require('./creative_library/social_section/blogs.png'),
    },
    promoSection: {
      webPromo: require('./creative_library/promo_section/web_promo.png'),
      mobilePromo: require('./creative_library/promo_section/mobile_promo.png'),
    },
    practicesSection: {
      goodPractices: require('./creative_library/practices_section/good_practices.png'),
      badPractices: require('./creative_library/practices_section/bad_practices.png'),
    },
  },
  emotions: {
    anger: require('./emotions/anger.gif'),
    anger_preview: require('./emotions/anger_preview.jpg'),
    contempt: require('./emotions/contempt.gif'),
    contempt_preview: require('./emotions/contempt_preview.jpg'),
    disgust: require('./emotions/disgust.gif'),
    disgust_preview: require('./emotions/disgust_preview.jpg'),
    fear: require('./emotions/fear.gif'),
    fear_preview: require('./emotions/fear_preview.jpg'),
    happiness: require('./emotions/happiness.gif'),
    happiness_preview: require('./emotions/happiness_preview.jpg'),
    neutral: require('./emotions/neutral.gif'),
    neutral_preview: require('./emotions/neutral_preview.jpg'),
    sadness: require('./emotions/sadness.gif'),
    sadness_preview: require('./emotions/sadness_preview.jpg'),
    surprise: require('./emotions/surprise.gif'),
    surprise_preview: require('./emotions/surprise_preview.jpg'),
  },
  card: {
    joinMainnet: require('./card/joinMainnet.png'),
    wallet: require('./card/wallet.png'),
  },
  quiz: {
    quizFailed: require('./quiz/quiz_failed.png'),
    quiz: require('./quiz/quiz.png'),
    quiz_small: require('./quiz/quiz_small.png'),
  },
} as const;
