// SPDX-License-Identifier: ice License 1.0

export const Images = {
  tabbar: {
    itemBackground: require('./tabbar/item-background.png'),
    miningBackground: require('./tabbar/mining-background.png'),
  },
  roles: {
    ambassador: require('./roles/ambassador.png'),
    // TODO: Add actual image once needed
    ambassadorInactive: require('./roles/pioneer-inactive.png'),
    snowman: require('./roles/pioneer.png'),
    snowmanInactive: require('./roles/pioneer-inactive.png'),
  },
  badges: {
    /*
      path to the badges are generating dynamicly and based on the data from the response
      ${type}${arrayIndex}_achieved_${achieved}
    */
    social0_achieved_true: require('./badges/iceBreaker.png'),
    social1_achieved_true: require('./badges/TroubleMaker.png'),
    social2_achieved_true: require('./badges/SnowyPlower.png'),
    social3_achieved_true: require('./badges/ArcticPrankster.png'),
    social4_achieved_true: require('./badges/GlacialPolly.png'),
    social5_achieved_true: require('./badges/FrostySmacker.png'),
    social6_achieved_true: require('./badges/PolarMachine.png'),
    social7_achieved_true: require('./badges/NorthStorm.png'),
    social8_achieved_true: require('./badges/SnowFall.png'),
    social9_achieved_true: require('./badges/iceLegend.png'),
    social0_achieved_false: require('./badges/iceBreakerInactive.png'),
    social1_achieved_false: require('./badges/TroubleMakerInactive.png'),
    social2_achieved_false: require('./badges/SnowyPlowerInactive.png'),
    social3_achieved_false: require('./badges/ArcticPranksterInactive.png'),
    social4_achieved_false: require('./badges/GlacialPollyInactive.png'),
    social5_achieved_false: require('./badges/FrostySmackerInactive.png'),
    social6_achieved_false: require('./badges/PolarMachineInactive.png'),
    social7_achieved_false: require('./badges/NorthStormInactive.png'),
    social8_achieved_false: require('./badges/SnowFallInactive.png'),
    social9_achieved_false: require('./badges/iceLegendInactive.png'),
    coin0_achieved_true: require('./badges/PoorGeorge.png'),
    coin1_achieved_true: require('./badges/FrozenPurse.png'),
    coin2_achieved_true: require('./badges/ArcticAssistant.png'),
    coin3_achieved_true: require('./badges/iceCubeSwagger.png'),
    coin4_achieved_true: require('./badges/PolarConsultant.png'),
    coin5_achieved_true: require('./badges/IglooBroker.png'),
    coin6_achieved_true: require('./badges/SnowyAccountant.png'),
    coin7_achieved_true: require('./badges/WinterBanker.png'),
    coin8_achieved_true: require('./badges/ColdDirector.png'),
    coin9_achieved_true: require('./badges/RichieRich.png'),
    coin0_achieved_false: require('./badges/PoorGeorgeInactive.png'),
    coin1_achieved_false: require('./badges/FrozenPurseInactive.png'),
    coin2_achieved_false: require('./badges/ArcticAssistantInactive.png'),
    coin3_achieved_false: require('./badges/iceCubeSwaggerInactive.png'),
    coin4_achieved_false: require('./badges/PolarConsultantInactive.png'),
    coin5_achieved_false: require('./badges/IglooBrokerInactive.png'),
    coin6_achieved_false: require('./badges/SnowyAccountantInactive.png'),
    coin7_achieved_false: require('./badges/WinterBankerInactive.png'),
    coin8_achieved_false: require('./badges/ColdDirectorInactive.png'),
    coin9_achieved_false: require('./badges/RichieRichInactive.png'),
    level0_achieved_true: require('./badges/iceSoldier.png'),
    level1_achieved_true: require('./badges/WindSergeant.png'),
    level2_achieved_true: require('./badges/SnowLieutenant.png'),
    level3_achieved_true: require('./badges/FlakeColonel.png'),
    level4_achieved_true: require('./badges/FrostGeneral.png'),
    level5_achieved_true: require('./badges/iceCommander.png'),
    level0_achieved_false: require('./badges/iceSoldierInactive.png'),
    level1_achieved_false: require('./badges/WindSergeantInactive.png'),
    level2_achieved_false: require('./badges/SnowLieutenantInactive.png'),
    level3_achieved_false: require('./badges/FlakeColonelInactive.png'),
    level4_achieved_false: require('./badges/FrostGeneralInactive.png'),
    level5_achieved_false: require('./badges/iceCommanderInactive.png'),
  },
  phone: {
    confirmPhoneNumber: require('./phone/confirmPhoneNumber.png'),
    modifyPhoneNumber: require('./phone/modifyPhoneNumber.png'),
  },
  backgrounds: {
    linesBg: require('./backgrounds/linesBg.png'),
    privacyBgTop: require('./backgrounds/privacyBgTop.png'),
    privacyBgMiddle: require('./backgrounds/privacyBgMiddle.png'),
    privacyBgBottom: require('./backgrounds/privacyBgBottom.png'),
    linesHeaderBg: require('./backgrounds/linesHeaderBg.png'),
    adoptionCardBg: require('./backgrounds/adoptionCardBg.png'),
    levelCardBg: require('./backgrounds/levelCardBg.png'),
    referralsCardBg: require('./backgrounds/referralsCardBg.png'),
    walkthroughBg: require('./backgrounds/walkthrough.png'),
  },
  popUp: {
    updateRequired: require('./popup/please_update.png'),
    error: require('./popup/oops.png'),
    upToDate: require('./popup/already_updated.png'),
    resurrection: require('./popup/resurrection.png'),
    telegram: require('./popup/telegram.png'),
    earlyAccess: require('./popup/earlyAccess.png'),
  },
} as const;
