// SPDX-License-Identifier: ice License 1.0

import {ImageRequireSource} from 'react-native';

export type CountryFlagAbbreviation =
  | 'ad'
  | 'ae'
  | 'af'
  | 'ag'
  | 'ai'
  | 'al'
  | 'am'
  | 'ao'
  | 'aq'
  | 'ar'
  | 'as'
  | 'at'
  | 'au'
  | 'aw'
  | 'ax'
  | 'az'
  | 'ba'
  | 'bb'
  | 'bd'
  | 'be'
  | 'bf'
  | 'bg'
  | 'bh'
  | 'bi'
  | 'bj'
  | 'bl'
  | 'bm'
  | 'bn'
  | 'bo'
  | 'bq'
  | 'br'
  | 'bs'
  | 'bt'
  | 'bv'
  | 'bw'
  | 'by'
  | 'bz'
  | 'ca'
  | 'cc'
  | 'cd'
  | 'cf'
  | 'cg'
  | 'ch'
  | 'ci'
  | 'ck'
  | 'cl'
  | 'cm'
  | 'cn'
  | 'co'
  | 'cr'
  | 'cu'
  | 'cv'
  | 'cw'
  | 'cx'
  | 'cy'
  | 'cz'
  | 'de'
  | 'dj'
  | 'dk'
  | 'dm'
  | 'do'
  | 'dz'
  | 'ec'
  | 'ee'
  | 'eg'
  | 'eh'
  | 'er'
  | 'es'
  | 'et'
  | 'eu'
  | 'fi'
  | 'fj'
  | 'fk'
  | 'fm'
  | 'fo'
  | 'fr'
  | 'ga'
  | 'gb'
  | 'gd'
  | 'ge'
  | 'gf'
  | 'gg'
  | 'gh'
  | 'gi'
  | 'gl'
  | 'gm'
  | 'gn'
  | 'gp'
  | 'gq'
  | 'gr'
  | 'gs'
  | 'gt'
  | 'gu'
  | 'gw'
  | 'gy'
  | 'hk'
  | 'hm'
  | 'hn'
  | 'hr'
  | 'ht'
  | 'hu'
  | 'id'
  | 'ie'
  | 'il'
  | 'im'
  | 'in'
  | 'io'
  | 'iq'
  | 'ir'
  | 'is'
  | 'it'
  | 'je'
  | 'jm'
  | 'jo'
  | 'jp'
  | 'ke'
  | 'kg'
  | 'kh'
  | 'ki'
  | 'km'
  | 'kn'
  | 'kp'
  | 'kr'
  | 'kw'
  | 'ky'
  | 'kz'
  | 'la'
  | 'lb'
  | 'lc'
  | 'li'
  | 'lk'
  | 'lr'
  | 'ls'
  | 'lt'
  | 'lu'
  | 'lv'
  | 'ly'
  | 'ma'
  | 'mc'
  | 'md'
  | 'me'
  | 'mf'
  | 'mg'
  | 'mh'
  | 'mk'
  | 'ml'
  | 'mm'
  | 'mn'
  | 'mo'
  | 'mp'
  | 'mq'
  | 'mr'
  | 'ms'
  | 'mt'
  | 'mu'
  | 'mv'
  | 'mw'
  | 'mx'
  | 'my'
  | 'mz'
  | 'na'
  | 'nc'
  | 'ne'
  | 'nf'
  | 'ng'
  | 'ni'
  | 'nl'
  | 'no'
  | 'np'
  | 'nr'
  | 'nu'
  | 'nz'
  | 'om'
  | 'pa'
  | 'pe'
  | 'pf'
  | 'pg'
  | 'ph'
  | 'pk'
  | 'pl'
  | 'pm'
  | 'pn'
  | 'pr'
  | 'ps'
  | 'pt'
  | 'pw'
  | 'py'
  | 'qa'
  | 're'
  | 'ro'
  | 'rs'
  | 'ru'
  | 'rw'
  | 'sa'
  | 'sb'
  | 'sc'
  | 'sd'
  | 'se'
  | 'sg'
  | 'sh'
  | 'si'
  | 'sj'
  | 'sk'
  | 'sl'
  | 'sm'
  | 'sn'
  | 'so'
  | 'sr'
  | 'ss'
  | 'st'
  | 'sv'
  | 'sx'
  | 'sy'
  | 'sz'
  | 'tc'
  | 'td'
  | 'tf'
  | 'tg'
  | 'th'
  | 'tj'
  | 'tk'
  | 'tl'
  | 'tm'
  | 'tn'
  | 'to'
  | 'tr'
  | 'tt'
  | 'tv'
  | 'tw'
  | 'tz'
  | 'ua'
  | 'ug'
  | 'um'
  | 'us'
  | 'uy'
  | 'uz'
  | 'va'
  | 'vc'
  | 've'
  | 'vg'
  | 'vi'
  | 'vn'
  | 'vu'
  | 'wf'
  | 'ws'
  | 'xk'
  | 'ye'
  | 'yt'
  | 'za'
  | 'zm'
  | 'zw'
  | 'arabic';

type Flags = {
  [key in CountryFlagAbbreviation]: ImageRequireSource;
};

export const flags: Flags = {
  ad: require('./assets/ad.png'),
  ae: require('./assets/ae.png'),
  af: require('./assets/af.png'),
  ag: require('./assets/ag.png'),
  ai: require('./assets/ai.png'),
  al: require('./assets/al.png'),
  am: require('./assets/am.png'),
  ao: require('./assets/ao.png'),
  aq: require('./assets/aq.png'),
  ar: require('./assets/ar.png'),
  as: require('./assets/as.png'),
  at: require('./assets/at.png'),
  au: require('./assets/au.png'),
  aw: require('./assets/aw.png'),
  ax: require('./assets/ax.png'),
  az: require('./assets/az.png'),
  ba: require('./assets/ba.png'),
  bb: require('./assets/bb.png'),
  bd: require('./assets/bd.png'),
  be: require('./assets/be.png'),
  bf: require('./assets/bf.png'),
  bg: require('./assets/bg.png'),
  bh: require('./assets/bh.png'),
  bi: require('./assets/bi.png'),
  bj: require('./assets/bj.png'),
  bl: require('./assets/bl.png'),
  bm: require('./assets/bm.png'),
  bn: require('./assets/bn.png'),
  bo: require('./assets/bo.png'),
  bq: require('./assets/bq.png'),
  br: require('./assets/br.png'),
  bs: require('./assets/bs.png'),
  bt: require('./assets/bt.png'),
  bv: require('./assets/bv.png'),
  bw: require('./assets/bw.png'),
  by: require('./assets/by.png'),
  bz: require('./assets/bz.png'),
  ca: require('./assets/ca.png'),
  cc: require('./assets/cc.png'),
  cd: require('./assets/cd.png'),
  cf: require('./assets/cf.png'),
  cg: require('./assets/cg.png'),
  ch: require('./assets/ch.png'),
  ci: require('./assets/ci.png'),
  ck: require('./assets/ck.png'),
  cl: require('./assets/cl.png'),
  cm: require('./assets/cm.png'),
  cn: require('./assets/cn.png'),
  co: require('./assets/co.png'),
  cr: require('./assets/cr.png'),
  cu: require('./assets/cu.png'),
  cv: require('./assets/cv.png'),
  cw: require('./assets/cw.png'),
  cx: require('./assets/cx.png'),
  cy: require('./assets/cy.png'),
  cz: require('./assets/cz.png'),
  de: require('./assets/de.png'),
  dj: require('./assets/dj.png'),
  dk: require('./assets/dk.png'),
  dm: require('./assets/dm.png'),
  do: require('./assets/do.png'),
  dz: require('./assets/dz.png'),
  ec: require('./assets/ec.png'),
  ee: require('./assets/ee.png'),
  eg: require('./assets/eg.png'),
  eh: require('./assets/eh.png'),
  er: require('./assets/er.png'),
  es: require('./assets/es.png'),
  et: require('./assets/et.png'),
  eu: require('./assets/eu.png'),
  fi: require('./assets/fi.png'),
  fj: require('./assets/fj.png'),
  fk: require('./assets/fk.png'),
  fm: require('./assets/fm.png'),
  fo: require('./assets/fo.png'),
  fr: require('./assets/fr.png'),
  ga: require('./assets/ga.png'),
  gb: require('./assets/gb.png'),
  gd: require('./assets/gd.png'),
  ge: require('./assets/ge.png'),
  gf: require('./assets/gf.png'),
  gg: require('./assets/gg.png'),
  gh: require('./assets/gh.png'),
  gi: require('./assets/gi.png'),
  gl: require('./assets/gl.png'),
  gm: require('./assets/gm.png'),
  gn: require('./assets/gn.png'),
  gp: require('./assets/gp.png'),
  gq: require('./assets/gq.png'),
  gr: require('./assets/gr.png'),
  gs: require('./assets/gs.png'),
  gt: require('./assets/gt.png'),
  gu: require('./assets/gu.png'),
  gw: require('./assets/gw.png'),
  gy: require('./assets/gy.png'),
  hk: require('./assets/hk.png'),
  hm: require('./assets/hm.png'),
  hn: require('./assets/hn.png'),
  hr: require('./assets/hr.png'),
  ht: require('./assets/ht.png'),
  hu: require('./assets/hu.png'),
  id: require('./assets/id.png'),
  ie: require('./assets/ie.png'),
  il: require('./assets/il.png'),
  im: require('./assets/im.png'),
  in: require('./assets/in.png'),
  io: require('./assets/io.png'),
  iq: require('./assets/iq.png'),
  ir: require('./assets/ir.png'),
  is: require('./assets/is.png'),
  it: require('./assets/it.png'),
  je: require('./assets/je.png'),
  jm: require('./assets/jm.png'),
  jo: require('./assets/jo.png'),
  jp: require('./assets/jp.png'),
  ke: require('./assets/ke.png'),
  kg: require('./assets/kg.png'),
  kh: require('./assets/kh.png'),
  ki: require('./assets/ki.png'),
  km: require('./assets/km.png'),
  kn: require('./assets/kn.png'),
  kp: require('./assets/kp.png'),
  kr: require('./assets/kr.png'),
  kw: require('./assets/kw.png'),
  ky: require('./assets/ky.png'),
  kz: require('./assets/kz.png'),
  la: require('./assets/la.png'),
  lb: require('./assets/lb.png'),
  lc: require('./assets/lc.png'),
  li: require('./assets/li.png'),
  lk: require('./assets/lk.png'),
  lr: require('./assets/lr.png'),
  ls: require('./assets/ls.png'),
  lt: require('./assets/lt.png'),
  lu: require('./assets/lu.png'),
  lv: require('./assets/lv.png'),
  ly: require('./assets/ly.png'),
  ma: require('./assets/ma.png'),
  mc: require('./assets/mc.png'),
  md: require('./assets/md.png'),
  me: require('./assets/me.png'),
  mf: require('./assets/mf.png'),
  mg: require('./assets/mg.png'),
  mh: require('./assets/mh.png'),
  mk: require('./assets/mk.png'),
  ml: require('./assets/ml.png'),
  mm: require('./assets/mm.png'),
  mn: require('./assets/mn.png'),
  mo: require('./assets/mo.png'),
  mp: require('./assets/mp.png'),
  mq: require('./assets/mq.png'),
  mr: require('./assets/mr.png'),
  ms: require('./assets/ms.png'),
  mt: require('./assets/mt.png'),
  mu: require('./assets/mu.png'),
  mv: require('./assets/mv.png'),
  mw: require('./assets/mw.png'),
  mx: require('./assets/mx.png'),
  my: require('./assets/my.png'),
  mz: require('./assets/mz.png'),
  na: require('./assets/na.png'),
  nc: require('./assets/nc.png'),
  ne: require('./assets/ne.png'),
  nf: require('./assets/nf.png'),
  ng: require('./assets/ng.png'),
  ni: require('./assets/ni.png'),
  nl: require('./assets/nl.png'),
  no: require('./assets/no.png'),
  np: require('./assets/np.png'),
  nr: require('./assets/nr.png'),
  nu: require('./assets/nu.png'),
  nz: require('./assets/nz.png'),
  om: require('./assets/om.png'),
  pa: require('./assets/pa.png'),
  pe: require('./assets/pe.png'),
  pf: require('./assets/pf.png'),
  pg: require('./assets/pg.png'),
  ph: require('./assets/ph.png'),
  pk: require('./assets/pk.png'),
  pl: require('./assets/pl.png'),
  pm: require('./assets/pm.png'),
  pn: require('./assets/pn.png'),
  pr: require('./assets/pr.png'),
  ps: require('./assets/ps.png'),
  pt: require('./assets/pt.png'),
  pw: require('./assets/pw.png'),
  py: require('./assets/py.png'),
  qa: require('./assets/qa.png'),
  re: require('./assets/re.png'),
  ro: require('./assets/ro.png'),
  rs: require('./assets/rs.png'),
  ru: require('./assets/ru.png'),
  rw: require('./assets/rw.png'),
  sa: require('./assets/sa.png'),
  sb: require('./assets/sb.png'),
  sc: require('./assets/sc.png'),
  sd: require('./assets/sd.png'),
  se: require('./assets/se.png'),
  sg: require('./assets/sg.png'),
  sh: require('./assets/sh.png'),
  si: require('./assets/si.png'),
  sj: require('./assets/sj.png'),
  sk: require('./assets/sk.png'),
  sl: require('./assets/sl.png'),
  sm: require('./assets/sm.png'),
  sn: require('./assets/sn.png'),
  so: require('./assets/so.png'),
  sr: require('./assets/sr.png'),
  ss: require('./assets/ss.png'),
  st: require('./assets/st.png'),
  sv: require('./assets/sv.png'),
  sx: require('./assets/sx.png'),
  sy: require('./assets/sy.png'),
  sz: require('./assets/sz.png'),
  tc: require('./assets/tc.png'),
  td: require('./assets/td.png'),
  tf: require('./assets/tf.png'),
  tg: require('./assets/tg.png'),
  th: require('./assets/th.png'),
  tj: require('./assets/tj.png'),
  tk: require('./assets/tk.png'),
  tl: require('./assets/tl.png'),
  tm: require('./assets/tm.png'),
  tn: require('./assets/tn.png'),
  to: require('./assets/to.png'),
  tr: require('./assets/tr.png'),
  tt: require('./assets/tt.png'),
  tv: require('./assets/tv.png'),
  tw: require('./assets/tw.png'),
  tz: require('./assets/tz.png'),
  ua: require('./assets/ua.png'),
  ug: require('./assets/ug.png'),
  um: require('./assets/um.png'),
  us: require('./assets/us.png'),
  uy: require('./assets/uy.png'),
  uz: require('./assets/uz.png'),
  va: require('./assets/va.png'),
  vc: require('./assets/vc.png'),
  ve: require('./assets/ve.png'),
  vg: require('./assets/vg.png'),
  vi: require('./assets/vi.png'),
  vn: require('./assets/vn.png'),
  vu: require('./assets/vu.png'),
  wf: require('./assets/wf.png'),
  ws: require('./assets/ws.png'),
  xk: require('./assets/xk.png'),
  ye: require('./assets/ye.png'),
  yt: require('./assets/yt.png'),
  za: require('./assets/za.png'),
  zm: require('./assets/zm.png'),
  zw: require('./assets/zw.png'),
  arabic: require('./assets/arabic.png'),
};
