// SPDX-License-Identifier: ice License 1.0

export interface Country {
  name: string;
  flag: string;
  isoCode: string;
  iddCode: string;
}

export const countries: Country[] = [
  {
    name: 'Andorra',
    flag: '🇦🇩',
    isoCode: 'AD',
    iddCode: '+376',
  },
  {
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    isoCode: 'AE',
    iddCode: '+971',
  },
  {
    name: 'Afghanistan',
    flag: '🇦🇫',
    isoCode: 'AF',
    iddCode: '+93',
  },
  {
    name: 'Antigua and Barbuda',
    flag: '🇦🇬',
    isoCode: 'AG',
    iddCode: '+1',
  },
  {
    name: 'Anguilla',
    flag: '🇦🇮',
    isoCode: 'AI',
    iddCode: '+1',
  },
  {
    name: 'Albania',
    flag: '🇦🇱',
    isoCode: 'AL',
    iddCode: '+355',
  },
  {
    name: 'Armenia',
    flag: '🇦🇲',
    isoCode: 'AM',
    iddCode: '+374',
  },
  {
    name: 'Angola',
    flag: '🇦🇴',
    isoCode: 'AO',
    iddCode: '+244',
  },
  {
    name: 'Antarctica',
    flag: '🇦🇶',
    isoCode: 'AQ',
    iddCode: '+672',
  },
  {
    name: 'Argentina',
    flag: '🇦🇷',
    isoCode: 'AR',
    iddCode: '+54',
  },
  {
    name: 'American Samoa',
    flag: '🇦🇸',
    isoCode: 'AS',
    iddCode: '+1',
  },
  {
    name: 'Austria',
    flag: '🇦🇹',
    isoCode: 'AT',
    iddCode: '+43',
  },
  {
    name: 'Australia',
    flag: '🇦🇺',
    isoCode: 'AU',
    iddCode: '+61',
  },
  {
    name: 'Aruba',
    flag: '🇦🇼',
    isoCode: 'AW',
    iddCode: '+297',
  },
  {
    name: 'Aland Islands',
    flag: '🇦🇽',
    isoCode: 'AX',
    iddCode: '+358',
  },
  {
    name: 'Azerbaijan',
    flag: '🇦🇿',
    isoCode: 'AZ',
    iddCode: '+994',
  },
  {
    name: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    isoCode: 'BA',
    iddCode: '+387',
  },
  {
    name: 'Barbados',
    flag: '🇧🇧',
    isoCode: 'BB',
    iddCode: '+1',
  },
  {
    name: 'Bangladesh',
    flag: '🇧🇩',
    isoCode: 'BD',
    iddCode: '+880',
  },
  {
    name: 'Belgium',
    flag: '🇧🇪',
    isoCode: 'BE',
    iddCode: '+32',
  },
  {
    name: 'Burkina Faso',
    flag: '🇧🇫',
    isoCode: 'BF',
    iddCode: '+226',
  },
  {
    name: 'Bulgaria',
    flag: '🇧🇬',
    isoCode: 'BG',
    iddCode: '+359',
  },
  {
    name: 'Bahrain',
    flag: '🇧🇭',
    isoCode: 'BH',
    iddCode: '+973',
  },
  {
    name: 'Burundi',
    flag: '🇧🇮',
    isoCode: 'BI',
    iddCode: '+257',
  },
  {
    name: 'Benin',
    flag: '🇧🇯',
    isoCode: 'BJ',
    iddCode: '+229',
  },
  {
    name: 'Saint Barthelemy',
    flag: '🇧🇱',
    isoCode: 'BL',
    iddCode: '+590',
  },
  {
    name: 'Bermuda',
    flag: '🇧🇲',
    isoCode: 'BM',
    iddCode: '+1',
  },
  {
    name: 'Brunei Darussalam',
    flag: '🇧🇳',
    isoCode: 'BN',
    iddCode: '+673',
  },
  {
    name: 'Bolivia',
    flag: '🇧🇴',
    isoCode: 'BO',
    iddCode: '+591',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    flag: '🇧🇶',
    isoCode: 'BQ',
    iddCode: '+599',
  },
  {
    name: 'Brazil',
    flag: '🇧🇷',
    isoCode: 'BR',
    iddCode: '+55',
  },
  {
    name: 'Bahamas',
    flag: '🇧🇸',
    isoCode: 'BS',
    iddCode: '+1',
  },
  {
    name: 'Bhutan',
    flag: '🇧🇹',
    isoCode: 'BT',
    iddCode: '+975',
  },
  {
    name: 'Bouvet Island',
    flag: '🇧🇻',
    isoCode: 'BV',
    iddCode: '+55',
  },
  {
    name: 'Botswana',
    flag: '🇧🇼',
    isoCode: 'BW',
    iddCode: '+267',
  },
  {
    name: 'Belarus',
    flag: '🇧🇾',
    isoCode: 'BY',
    iddCode: '+375',
  },
  {
    name: 'Belize',
    flag: '🇧🇿',
    isoCode: 'BZ',
    iddCode: '+501',
  },
  {
    name: 'Canada',
    flag: '🇨🇦',
    isoCode: 'CA',
    iddCode: '+1',
  },
  {
    name: 'Cocos (Keeling) Islands',
    flag: '🇨🇨',
    isoCode: 'CC',
    iddCode: '+61',
  },
  {
    name: 'Democratic Republic of the Congo',
    flag: '🇨🇩',
    isoCode: 'CD',
    iddCode: '+243',
  },
  {
    name: 'Central African Republic',
    flag: '🇨🇫',
    isoCode: 'CF',
    iddCode: '+236',
  },
  {
    name: 'Congo',
    flag: '🇨🇬',
    isoCode: 'CG',
    iddCode: '+242',
  },
  {
    name: 'Switzerland',
    flag: '🇨🇭',
    isoCode: 'CH',
    iddCode: '+41',
  },
  {
    name: "Cote D'ivoire",
    flag: '🇨🇮',
    isoCode: 'CI',
    iddCode: '+225',
  },
  {
    name: 'Cook Islands',
    flag: '🇨🇰',
    isoCode: 'CK',
    iddCode: '+682',
  },
  {
    name: 'Chile',
    flag: '🇨🇱',
    isoCode: 'CL',
    iddCode: '+56',
  },
  {
    name: 'Cameroon',
    flag: '🇨🇲',
    isoCode: 'CM',
    iddCode: '+237',
  },
  {
    name: 'China',
    flag: '🇨🇳',
    isoCode: 'CN',
    iddCode: '+86',
  },
  {
    name: 'Colombia',
    flag: '🇨🇴',
    isoCode: 'CO',
    iddCode: '+57',
  },
  {
    name: 'Costa Rica',
    flag: '🇨🇷',
    isoCode: 'CR',
    iddCode: '+506',
  },
  {
    name: 'Cuba',
    flag: '🇨🇺',
    isoCode: 'CU',
    iddCode: '+53',
  },
  {
    name: 'Cabo Verde',
    flag: '🇨🇻',
    isoCode: 'CV',
    iddCode: '+238',
  },
  {
    name: 'Curacao',
    flag: '🇨🇼',
    isoCode: 'CW',
    iddCode: '+599',
  },
  {
    name: 'Christmas Island',
    flag: '🇨🇽',
    isoCode: 'CX',
    iddCode: '+61',
  },
  {
    name: 'Cyprus',
    flag: '🇨🇾',
    isoCode: 'CY',
    iddCode: '+357',
  },
  {
    name: 'Czechia',
    flag: '🇨🇿',
    isoCode: 'CZ',
    iddCode: '+420',
  },
  {
    name: 'Germany',
    flag: '🇩🇪',
    isoCode: 'DE',
    iddCode: '+49',
  },
  {
    name: 'Djibouti',
    flag: '🇩🇯',
    isoCode: 'DJ',
    iddCode: '+253',
  },
  {
    name: 'Denmark',
    flag: '🇩🇰',
    isoCode: 'DK',
    iddCode: '+45',
  },
  {
    name: 'Dominica',
    flag: '🇩🇲',
    isoCode: 'DM',
    iddCode: '+1',
  },
  {
    name: 'Dominican Republic',
    flag: '🇩🇴',
    isoCode: 'DO',
    iddCode: '+1',
  },
  {
    name: 'Algeria',
    flag: '🇩🇿',
    isoCode: 'DZ',
    iddCode: '+213',
  },
  {
    name: 'Ecuador',
    flag: '🇪🇨',
    isoCode: 'EC',
    iddCode: '+593',
  },
  {
    name: 'Estonia',
    flag: '🇪🇪',
    isoCode: 'EE',
    iddCode: '+372',
  },
  {
    name: 'Egypt',
    flag: '🇪🇬',
    isoCode: 'EG',
    iddCode: '+20',
  },
  {
    name: 'Western Sahara',
    flag: '🇪🇭',
    isoCode: 'EH',
    iddCode: '+212',
  },
  {
    name: 'Eritrea',
    flag: '🇪🇷',
    isoCode: 'ER',
    iddCode: '+291',
  },
  {
    name: 'Spain',
    flag: '🇪🇸',
    isoCode: 'ES',
    iddCode: '+34',
  },
  {
    name: 'Ethiopia',
    flag: '🇪🇹',
    isoCode: 'ET',
    iddCode: '+251',
  },
  {
    name: 'Finland',
    flag: '🇫🇮',
    isoCode: 'FI',
    iddCode: '+358',
  },
  {
    name: 'Fiji',
    flag: '🇫🇯',
    isoCode: 'FJ',
    iddCode: '+679',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    flag: '🇫🇰',
    isoCode: 'FK',
    iddCode: '+500',
  },
  {
    name: 'Federated States of Micronesia',
    flag: '🇫🇲',
    isoCode: 'FM',
    iddCode: '+691',
  },
  {
    name: 'Faroe Islands',
    flag: '🇫🇴',
    isoCode: 'FO',
    iddCode: '+298',
  },
  {
    name: 'France',
    flag: '🇫🇷',
    isoCode: 'FR',
    iddCode: '+33',
  },
  {
    name: 'Gabon',
    flag: '🇬🇦',
    isoCode: 'GA',
    iddCode: '+241',
  },
  {
    name: 'United Kingdom',
    flag: '🇬🇧',
    isoCode: 'GB',
    iddCode: '+44',
  },
  {
    name: 'Grenada',
    flag: '🇬🇩',
    isoCode: 'GD',
    iddCode: '+1',
  },
  {
    name: 'Georgia',
    flag: '🇬🇪',
    isoCode: 'GE',
    iddCode: '+995',
  },
  {
    name: 'French Guiana',
    flag: '🇬🇫',
    isoCode: 'GF',
    iddCode: '+594',
  },
  {
    name: 'Guernsey',
    flag: '🇬🇬',
    isoCode: 'GG',
    iddCode: '+44',
  },
  {
    name: 'Ghana',
    flag: '🇬🇭',
    isoCode: 'GH',
    iddCode: '+233',
  },
  {
    name: 'Gibraltar',
    flag: '🇬🇮',
    isoCode: 'GI',
    iddCode: '+350',
  },
  {
    name: 'Greenland',
    flag: '🇬🇱',
    isoCode: 'GL',
    iddCode: '+299',
  },
  {
    name: 'Gambia',
    flag: '🇬🇲',
    isoCode: 'GM',
    iddCode: '+220',
  },
  {
    name: 'Guinea',
    flag: '🇬🇳',
    isoCode: 'GN',
    iddCode: '+224',
  },
  {
    name: 'Guadeloupe',
    flag: '🇬🇵',
    isoCode: 'GP',
    iddCode: '+590',
  },
  {
    name: 'Equatorial Guinea',
    flag: '🇬🇶',
    isoCode: 'GQ',
    iddCode: '+240',
  },
  {
    name: 'Greece',
    flag: '🇬🇷',
    isoCode: 'GR',
    iddCode: '+30',
  },
  {
    name: 'South Georgia and The South Sandwich Islands',
    flag: '🇬🇸',
    isoCode: 'GS',
    iddCode: '+500',
  },
  {
    name: 'Guatemala',
    flag: '🇬🇹',
    isoCode: 'GT',
    iddCode: '+502',
  },
  {
    name: 'Guam',
    flag: '🇬🇺',
    isoCode: 'GU',
    iddCode: '+1',
  },
  {
    name: 'Guinea-Bissau',
    flag: '🇬🇼',
    isoCode: 'GW',
    iddCode: '+245',
  },
  {
    name: 'Guyana',
    flag: '🇬🇾',
    isoCode: 'GY',
    iddCode: '+592',
  },
  {
    name: 'Hong Kong',
    flag: '🇭🇰',
    isoCode: 'HK',
    iddCode: '+852',
  },
  {
    name: 'Heard Island and Mcdonald Islands',
    flag: '🇭🇲',
    isoCode: 'HM',
    iddCode: '+672',
  },
  {
    name: 'Honduras',
    flag: '🇭🇳',
    isoCode: 'HN',
    iddCode: '+504',
  },
  {
    name: 'Croatia',
    flag: '🇭🇷',
    isoCode: 'HR',
    iddCode: '+385',
  },
  {
    name: 'Haiti',
    flag: '🇭🇹',
    isoCode: 'HT',
    iddCode: '+509',
  },
  {
    name: 'Hungary',
    flag: '🇭🇺',
    isoCode: 'HU',
    iddCode: '+36',
  },
  {
    name: 'Indonesia',
    flag: '🇮🇩',
    isoCode: 'ID',
    iddCode: '+62',
  },
  {
    name: 'Ireland',
    flag: '🇮🇪',
    isoCode: 'IE',
    iddCode: '+353',
  },
  {
    name: 'Israel',
    flag: '🇮🇱',
    isoCode: 'IL',
    iddCode: '+972',
  },
  {
    name: 'Isle of Man',
    flag: '🇮🇲',
    isoCode: 'IM',
    iddCode: '+44',
  },
  {
    name: 'India',
    flag: '🇮🇳',
    isoCode: 'IN',
    iddCode: '+91',
  },
  {
    name: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    isoCode: 'IO',
    iddCode: '+246',
  },
  {
    name: 'Iraq',
    flag: '🇮🇶',
    isoCode: 'IQ',
    iddCode: '+964',
  },
  {
    name: 'Islamic Republic of Iran',
    flag: '🇮🇷',
    isoCode: 'IR',
    iddCode: '+98',
  },
  {
    name: 'Iceland',
    flag: '🇮🇸',
    isoCode: 'IS',
    iddCode: '+354',
  },
  {
    name: 'Italy',
    flag: '🇮🇹',
    isoCode: 'IT',
    iddCode: '+39',
  },
  {
    name: 'Jersey',
    flag: '🇯🇪',
    isoCode: 'JE',
    iddCode: '+44',
  },
  {
    name: 'Jamaica',
    flag: '🇯🇲',
    isoCode: 'JM',
    iddCode: '+1',
  },
  {
    name: 'Jordan',
    flag: '🇯🇴',
    isoCode: 'JO',
    iddCode: '+962',
  },
  {
    name: 'Japan',
    flag: '🇯🇵',
    isoCode: 'JP',
    iddCode: '+81',
  },
  {
    name: 'Kenya',
    flag: '🇰🇪',
    isoCode: 'KE',
    iddCode: '+254',
  },
  {
    name: 'Kyrgyzstan',
    flag: '🇰🇬',
    isoCode: 'KG',
    iddCode: '+996',
  },
  {
    name: 'Cambodia',
    flag: '🇰🇭',
    isoCode: 'KH',
    iddCode: '+855',
  },
  {
    name: 'Kiribati',
    flag: '🇰🇮',
    isoCode: 'KI',
    iddCode: '+686',
  },
  {
    name: 'Comoros',
    flag: '🇰🇲',
    isoCode: 'KM',
    iddCode: '+269',
  },
  {
    name: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    isoCode: 'KN',
    iddCode: '+1',
  },
  {
    name: "Democratic People's Republic of Korea",
    flag: '🇰🇵',
    isoCode: 'KP',
    iddCode: '+850',
  },
  {
    name: 'Republic of Korea',
    flag: '🇰🇷',
    isoCode: 'KR',
    iddCode: '+82',
  },
  {
    name: 'Republic of Kosovo',
    flag: '🇽🇰',
    isoCode: 'XK',
    iddCode: '+383',
  },
  {
    name: 'Kuwait',
    flag: '🇰🇼',
    isoCode: 'KW',
    iddCode: '+965',
  },
  {
    name: 'Cayman Islands',
    flag: '🇰🇾',
    isoCode: 'KY',
    iddCode: '+1',
  },
  {
    name: 'Kazakhstan',
    flag: '🇰🇿',
    isoCode: 'KZ',
    iddCode: '+7',
  },
  {
    name: "Lao People's Democratic Republic",
    flag: '🇱🇦',
    isoCode: 'LA',
    iddCode: '+856',
  },
  {
    name: 'Lebanon',
    flag: '🇱🇧',
    isoCode: 'LB',
    iddCode: '+961',
  },
  {
    name: 'Saint Lucia',
    flag: '🇱🇨',
    isoCode: 'LC',
    iddCode: '+1',
  },
  {
    name: 'Liechtenstein',
    flag: '🇱🇮',
    isoCode: 'LI',
    iddCode: '+423',
  },
  {
    name: 'Sri Lanka',
    flag: '🇱🇰',
    isoCode: 'LK',
    iddCode: '+94',
  },
  {
    name: 'Liberia',
    flag: '🇱🇷',
    isoCode: 'LR',
    iddCode: '+231',
  },
  {
    name: 'Lesotho',
    flag: '🇱🇸',
    isoCode: 'LS',
    iddCode: '+266',
  },
  {
    name: 'Lithuania',
    flag: '🇱🇹',
    isoCode: 'LT',
    iddCode: '+370',
  },
  {
    name: 'Luxembourg',
    flag: '🇱🇺',
    isoCode: 'LU',
    iddCode: '+352',
  },
  {
    name: 'Latvia',
    flag: '🇱🇻',
    isoCode: 'LV',
    iddCode: '+371',
  },
  {
    name: 'Libya',
    flag: '🇱🇾',
    isoCode: 'LY',
    iddCode: '+218',
  },
  {
    name: 'Morocco',
    flag: '🇲🇦',
    isoCode: 'MA',
    iddCode: '+212',
  },
  {
    name: 'Monaco',
    flag: '🇲🇨',
    isoCode: 'MC',
    iddCode: '+377',
  },
  {
    name: 'Republic of Moldova',
    flag: '🇲🇩',
    isoCode: 'MD',
    iddCode: '+373',
  },
  {
    name: 'Montenegro',
    flag: '🇲🇪',
    isoCode: 'ME',
    iddCode: '+382',
  },
  {
    name: 'Saint Martin (French Part)',
    flag: '🇲🇫',
    isoCode: 'MF',
    iddCode: '+590',
  },
  {
    name: 'Madagascar',
    flag: '🇲🇬',
    isoCode: 'MG',
    iddCode: '+261',
  },
  {
    name: 'Marshall Islands',
    flag: '🇲🇭',
    isoCode: 'MH',
    iddCode: '+692',
  },
  {
    name: 'North Macedonia',
    flag: '🇲🇰',
    isoCode: 'MK',
    iddCode: '+389',
  },
  {
    name: 'Mali',
    flag: '🇲🇱',
    isoCode: 'ML',
    iddCode: '+223',
  },
  {
    name: 'Myanmar',
    flag: '🇲🇲',
    isoCode: 'MM',
    iddCode: '+95',
  },
  {
    name: 'Mongolia',
    flag: '🇲🇳',
    isoCode: 'MN',
    iddCode: '+976',
  },
  {
    name: 'Macao',
    flag: '🇲🇴',
    isoCode: 'MO',
    iddCode: '+853',
  },
  {
    name: 'Northern Mariana Islands',
    flag: '🇲🇵',
    isoCode: 'MP',
    iddCode: '+1',
  },
  {
    name: 'Martinique',
    flag: '🇲🇶',
    isoCode: 'MQ',
    iddCode: '+596',
  },
  {
    name: 'Mauritania',
    flag: '🇲🇷',
    isoCode: 'MR',
    iddCode: '+222',
  },
  {
    name: 'Montserrat',
    flag: '🇲🇸',
    isoCode: 'MS',
    iddCode: '+1',
  },
  {
    name: 'Malta',
    flag: '🇲🇹',
    isoCode: 'MT',
    iddCode: '+356',
  },
  {
    name: 'Mauritius',
    flag: '🇲🇺',
    isoCode: 'MU',
    iddCode: '+230',
  },
  {
    name: 'Maldives',
    flag: '🇲🇻',
    isoCode: 'MV',
    iddCode: '+960',
  },
  {
    name: 'Malawi',
    flag: '🇲🇼',
    isoCode: 'MW',
    iddCode: '+265',
  },
  {
    name: 'Mexico',
    flag: '🇲🇽',
    isoCode: 'MX',
    iddCode: '+52',
  },
  {
    name: 'Malaysia',
    flag: '🇲🇾',
    isoCode: 'MY',
    iddCode: '+60',
  },
  {
    name: 'Mozambique',
    flag: '🇲🇿',
    isoCode: 'MZ',
    iddCode: '+258',
  },
  {
    name: 'Namibia',
    flag: '🇳🇦',
    isoCode: 'NA',
    iddCode: '+264',
  },
  {
    name: 'New Caledonia',
    flag: '🇳🇨',
    isoCode: 'NC',
    iddCode: '+687',
  },
  {
    name: 'Niger',
    flag: '🇳🇪',
    isoCode: 'NE',
    iddCode: '+227',
  },
  {
    name: 'Norfolk Island',
    flag: '🇳🇫',
    isoCode: 'NF',
    iddCode: '+672',
  },
  {
    name: 'Nigeria',
    flag: '🇳🇬',
    isoCode: 'NG',
    iddCode: '+234',
  },
  {
    name: 'Nicaragua',
    flag: '🇳🇮',
    isoCode: 'NI',
    iddCode: '+505',
  },
  {
    name: 'Netherlands',
    flag: '🇳🇱',
    isoCode: 'NL',
    iddCode: '+31',
  },
  {
    name: 'Norway',
    flag: '🇳🇴',
    isoCode: 'NO',
    iddCode: '+47',
  },
  {
    name: 'Nepal',
    flag: '🇳🇵',
    isoCode: 'NP',
    iddCode: '+977',
  },
  {
    name: 'Nauru',
    flag: '🇳🇷',
    isoCode: 'NR',
    iddCode: '+674',
  },
  {
    name: 'Niue',
    flag: '🇳🇺',
    isoCode: 'NU',
    iddCode: '+683',
  },
  {
    name: 'New Zealand',
    flag: '🇳🇿',
    isoCode: 'NZ',
    iddCode: '+64',
  },
  {
    name: 'Oman',
    flag: '🇴🇲',
    isoCode: 'OM',
    iddCode: '+968',
  },
  {
    name: 'Panama',
    flag: '🇵🇦',
    isoCode: 'PA',
    iddCode: '+507',
  },
  {
    name: 'Peru',
    flag: '🇵🇪',
    isoCode: 'PE',
    iddCode: '+51',
  },
  {
    name: 'French Polynesia',
    flag: '🇵🇫',
    isoCode: 'PF',
    iddCode: '+689',
  },
  {
    name: 'Papua New Guinea',
    flag: '🇵🇬',
    isoCode: 'PG',
    iddCode: '+675',
  },
  {
    name: 'Philippines',
    flag: '🇵🇭',
    isoCode: 'PH',
    iddCode: '+63',
  },
  {
    name: 'Pakistan',
    flag: '🇵🇰',
    isoCode: 'PK',
    iddCode: '+92',
  },
  {
    name: 'Poland',
    flag: '🇵🇱',
    isoCode: 'PL',
    iddCode: '+48',
  },
  {
    name: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    isoCode: 'PM',
    iddCode: '+508',
  },
  {
    name: 'Pitcairn',
    flag: '🇵🇳',
    isoCode: 'PN',
    iddCode: '+64',
  },
  {
    name: 'Puerto Rico',
    flag: '🇵🇷',
    isoCode: 'PR',
    iddCode: '+1',
  },
  {
    name: 'State of Palestine',
    flag: '🇵🇸',
    isoCode: 'PS',
    iddCode: '+970',
  },
  {
    name: 'Portugal',
    flag: '🇵🇹',
    isoCode: 'PT',
    iddCode: '+351',
  },
  {
    name: 'Palau',
    flag: '🇵🇼',
    isoCode: 'PW',
    iddCode: '+680',
  },
  {
    name: 'Paraguay',
    flag: '🇵🇾',
    isoCode: 'PY',
    iddCode: '+595',
  },
  {
    name: 'Qatar',
    flag: '🇶🇦',
    isoCode: 'QA',
    iddCode: '+974',
  },
  {
    name: 'Reunion',
    flag: '🇷🇪',
    isoCode: 'RE',
    iddCode: '+262',
  },
  {
    name: 'Romania',
    flag: '🇷🇴',
    isoCode: 'RO',
    iddCode: '+40',
  },
  {
    name: 'Serbia',
    flag: '🇷🇸',
    isoCode: 'RS',
    iddCode: '+381',
  },
  {
    name: 'Russian Federation',
    flag: '🇷🇺',
    isoCode: 'RU',
    iddCode: '+7',
  },
  {
    name: 'Rwanda',
    flag: '🇷🇼',
    isoCode: 'RW',
    iddCode: '+250',
  },
  {
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    isoCode: 'SA',
    iddCode: '+966',
  },
  {
    name: 'Solomon Islands',
    flag: '🇸🇧',
    isoCode: 'SB',
    iddCode: '+677',
  },
  {
    name: 'Seychelles',
    flag: '🇸🇨',
    isoCode: 'SC',
    iddCode: '+248',
  },
  {
    name: 'Sudan',
    flag: '🇸🇩',
    isoCode: 'SD',
    iddCode: '+249',
  },
  {
    name: 'Sweden',
    flag: '🇸🇪',
    isoCode: 'SE',
    iddCode: '+46',
  },
  {
    name: 'Singapore',
    flag: '🇸🇬',
    isoCode: 'SG',
    iddCode: '+65',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    flag: '🇸🇭',
    isoCode: 'SH',
    iddCode: '+290',
  },
  {
    name: 'Slovenia',
    flag: '🇸🇮',
    isoCode: 'SI',
    iddCode: '+386',
  },
  {
    name: 'Svalbard and Jan Mayen',
    flag: '🇸🇯',
    isoCode: 'SJ',
    iddCode: '+47',
  },
  {
    name: 'Slovakia',
    flag: '🇸🇰',
    isoCode: 'SK',
    iddCode: '+421',
  },
  {
    name: 'Sierra Leone',
    flag: '🇸🇱',
    isoCode: 'SL',
    iddCode: '+232',
  },
  {
    name: 'San Marino',
    flag: '🇸🇲',
    isoCode: 'SM',
    iddCode: '+378',
  },
  {
    name: 'Senegal',
    flag: '🇸🇳',
    isoCode: 'SN',
    iddCode: '+221',
  },
  {
    name: 'Somalia',
    flag: '🇸🇴',
    isoCode: 'SO',
    iddCode: '+252',
  },
  {
    name: 'Suriname',
    flag: '🇸🇷',
    isoCode: 'SR',
    iddCode: '+597',
  },
  {
    name: 'South Sudan',
    flag: '🇸🇸',
    isoCode: 'SS',
    iddCode: '+211',
  },
  {
    name: 'Sao Tome and Principe',
    flag: '🇸🇹',
    isoCode: 'ST',
    iddCode: '+239',
  },
  {
    name: 'El Salvador',
    flag: '🇸🇻',
    isoCode: 'SV',
    iddCode: '+503',
  },
  {
    name: 'Sint Maarten (Dutch Part)',
    flag: '🇸🇽',
    isoCode: 'SX',
    iddCode: '+1',
  },
  {
    name: 'Syrian Arab Republic',
    flag: '🇸🇾',
    isoCode: 'SY',
    iddCode: '+963',
  },
  {
    name: 'Eswatini',
    flag: '🇸🇿',
    isoCode: 'SZ',
    iddCode: '+268',
  },
  {
    name: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    isoCode: 'TC',
    iddCode: '+1',
  },
  {
    name: 'Chad',
    flag: '🇹🇩',
    isoCode: 'TD',
    iddCode: '+235',
  },
  {
    name: 'French Southern Territories',
    flag: '🇹🇫',
    isoCode: 'TF',
    iddCode: '+672',
  },
  {
    name: 'Togo',
    flag: '🇹🇬',
    isoCode: 'TG',
    iddCode: '+228',
  },
  {
    name: 'Thailand',
    flag: '🇹🇭',
    isoCode: 'TH',
    iddCode: '+66',
  },
  {
    name: 'Tajikistan',
    flag: '🇹🇯',
    isoCode: 'TJ',
    iddCode: '+992',
  },
  {
    name: 'Tokelau',
    flag: '🇹🇰',
    isoCode: 'TK',
    iddCode: '+690',
  },
  {
    name: 'Timor-Leste',
    flag: '🇹🇱',
    isoCode: 'TL',
    iddCode: '+670',
  },
  {
    name: 'Turkmenistan',
    flag: '🇹🇲',
    isoCode: 'TM',
    iddCode: '+993',
  },
  {
    name: 'Tunisia',
    flag: '🇹🇳',
    isoCode: 'TN',
    iddCode: '+216',
  },
  {
    name: 'Tonga',
    flag: '🇹🇴',
    isoCode: 'TO',
    iddCode: '+676',
  },
  {
    name: 'Turkey',
    flag: '🇹🇷',
    isoCode: 'TR',
    iddCode: '+90',
  },
  {
    name: 'Trinidad and Tobago',
    flag: '🇹🇹',
    isoCode: 'TT',
    iddCode: '+1',
  },
  {
    name: 'Tuvalu',
    flag: '🇹🇻',
    isoCode: 'TV',
    iddCode: '+688',
  },
  {
    name: 'Taiwan (Province of China)',
    flag: '🇹🇼',
    isoCode: 'TW',
    iddCode: '+886',
  },
  {
    name: 'United Republic of Tanzania',
    flag: '🇹🇿',
    isoCode: 'TZ',
    iddCode: '+255',
  },
  {
    name: 'Ukraine',
    flag: '🇺🇦',
    isoCode: 'UA',
    iddCode: '+380',
  },
  {
    name: 'Uganda',
    flag: '🇺🇬',
    isoCode: 'UG',
    iddCode: '+256',
  },
  {
    name: 'United States Minor Outlying Islands',
    flag: '🇺🇲',
    isoCode: 'UM',
    iddCode: '+1',
  },
  {
    name: 'United States of America',
    flag: '🇺🇸',
    isoCode: 'US',
    iddCode: '+1',
  },
  {
    name: 'Uruguay',
    flag: '🇺🇾',
    isoCode: 'UY',
    iddCode: '+598',
  },
  {
    name: 'Uzbekistan',
    flag: '🇺🇿',
    isoCode: 'UZ',
    iddCode: '+998',
  },
  {
    name: 'Holy See',
    flag: '🇻🇦',
    isoCode: 'VA',
    iddCode: '+379',
  },
  {
    name: 'Saint Vincent and The Grenadines',
    flag: '🇻🇨',
    isoCode: 'VC',
    iddCode: '+1',
  },
  {
    name: 'Venezuela',
    flag: '🇻🇪',
    isoCode: 'VE',
    iddCode: '+58',
  },
  {
    name: 'British Virgin Islands',
    flag: '🇻🇬',
    isoCode: 'VG',
    iddCode: '+1',
  },
  {
    name: 'United States Virgin Islands',
    flag: '🇻🇮',
    isoCode: 'VI',
    iddCode: '+1',
  },
  {
    name: 'Viet Nam',
    flag: '🇻🇳',
    isoCode: 'VN',
    iddCode: '+84',
  },
  {
    name: 'Vanuatu',
    flag: '🇻🇺',
    isoCode: 'VU',
    iddCode: '+678',
  },
  {
    name: 'Wallis and Futuna',
    flag: '🇼🇫',
    isoCode: 'WF',
    iddCode: '+681',
  },
  {
    name: 'Samoa',
    flag: '🇼🇸',
    isoCode: 'WS',
    iddCode: '+685',
  },
  {
    name: 'Yemen',
    flag: '🇾🇪',
    isoCode: 'YE',
    iddCode: '+967',
  },
  {
    name: 'Mayotte',
    flag: '🇾🇹',
    isoCode: 'YT',
    iddCode: '+262',
  },
  {
    name: 'South Africa',
    flag: '🇿🇦',
    isoCode: 'ZA',
    iddCode: '+27',
  },
  {
    name: 'Zambia',
    flag: '🇿🇲',
    isoCode: 'ZM',
    iddCode: '+260',
  },
  {
    name: 'Zimbabwe',
    flag: '🇿🇼',
    isoCode: 'ZW',
    iddCode: '+263',
  },
];
