// SPDX-License-Identifier: ice License 1.0

import {ENV} from '@constants/env';

export const SMS_EMAIL_RESEND_TIMEOUT_SEC = 30;

export const DEVICE_METADATA_UPDATE_TIMEOUT_HOURS = 8;

export const MINING_LONG_PRESS_ACTIVATION_SEC = 1;

export const APP_AUTO_UPDATE_INTERVAL_SEC = ENV.APP_AUTO_UPDATE_INTERVAL_SEC;

export const HOME_REFRESH_MIN_INTERVAL_SEC = ENV.HOME_REFRESH_MIN_INTERVAL_SEC;

export const EMAIL_CODE_GET_STATUS_INTERVAL_SEC = 2;

export const SOCIALS_POPUP_INTERVAL_SEC = ENV.SOCIALS_POPUP_INTERVAL_SEC;

export const DEVICE_SENSORS_UPDATE_INTERVAL_MS = 500;

export const DEVICE_ANGLE_WARNING_FEEDBACK_INTERVAL_MS = 300;
