// SPDX-License-Identifier: BUSL-1.1

import {Contact} from 'react-native-contacts';

export const mockContacts: Contact[] = [
  {
    givenName: 'Alice',
    familyName: 'Alice',
    phoneNumbers: [
      {label: '+4 0728128471', number: '+4 0721005330'},
      {label: '+4 0728899080', number: '+4 0728899080'},
    ],
    recordID: 'contact_1',
    backTitle: '',
    emailAddresses: [],
    displayName: '',
    company: '',
    middleName: '',
    jobTitle: '',
    hasThumbnail: false,
    thumbnailPath: '',
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {day: 0, month: 0, year: 0},
    imAddresses: [],
    note: '',
  },
  {
    givenName: 'Aerial',
    familyName: 'Aerial',
    phoneNumbers: [{label: '+4 0711774775', number: '+4 0711774775'}],
    recordID: 'contact_2',
    backTitle: '',
    emailAddresses: [],
    displayName: '',
    company: '',
    middleName: '',
    jobTitle: '',
    hasThumbnail: false,
    thumbnailPath: '',
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {day: 0, month: 0, year: 0},
    imAddresses: [],
    note: '',
  },
  {
    givenName: 'Ada',
    familyName: 'Ada',
    phoneNumbers: [{label: '+4 0728069967', number: '+4 0728069967'}],
    recordID: 'contact_3',
    backTitle: '',
    emailAddresses: [],
    displayName: '',
    company: '',
    middleName: '',
    jobTitle: '',
    hasThumbnail: false,
    thumbnailPath: '',
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {day: 0, month: 0, year: 0},
    imAddresses: [],
    note: '',
  },
  {
    givenName: 'Alexis',
    familyName: 'Alexis',
    phoneNumbers: [{label: '+4 0728128471', number: '+4 0728128471'}],
    recordID: 'contact_4',
    backTitle: '',
    emailAddresses: [],
    displayName: '',
    company: '',
    middleName: '',
    jobTitle: '',
    hasThumbnail: false,
    thumbnailPath: '',
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {day: 0, month: 0, year: 0},
    imAddresses: [],
    note: '',
  },
  {
    givenName: 'Alexander',
    familyName: 'Alexander',
    phoneNumbers: [{label: '+4 0766214532', number: '+4 0766214532'}],
    recordID: 'contact_5',
    backTitle: '',
    emailAddresses: [],
    displayName: '',
    company: '',
    middleName: '',
    jobTitle: '',
    hasThumbnail: false,
    thumbnailPath: '',
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {day: 0, month: 0, year: 0},
    imAddresses: [],
    note: '',
  },
  {
    givenName: 'Beatrice',
    familyName: 'Beatrice',
    phoneNumbers: [{label: '+4 0745877590', number: '+4 0745877590'}],
    recordID: 'contact_6',
    backTitle: '',
    emailAddresses: [],
    displayName: '',
    company: '',
    middleName: '',
    jobTitle: '',
    hasThumbnail: false,
    thumbnailPath: '',
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {day: 0, month: 0, year: 0},
    imAddresses: [],
    note: '',
  },
  {
    givenName: 'Bernard',
    familyName: 'Bernard',
    phoneNumbers: [{label: '+4 0736221547', number: '+4 0736221547'}],
    recordID: 'contact_7',
    backTitle: '',
    emailAddresses: [],
    displayName: '',
    company: '',
    middleName: '',
    jobTitle: '',
    hasThumbnail: false,
    thumbnailPath: '',
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {day: 0, month: 0, year: 0},
    imAddresses: [],
    note: '',
  },
  {
    givenName: 'Boris',
    familyName: 'Boris',
    phoneNumbers: [{label: '+4 0718334592', number: '+4 0718334592'}],
    recordID: 'contact_8',
    backTitle: '',
    emailAddresses: [],
    displayName: '',
    company: '',
    middleName: '',
    jobTitle: '',
    hasThumbnail: false,
    thumbnailPath: '',
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {day: 0, month: 0, year: 0},
    imAddresses: [],
    note: '',
  },
];
