default_platform(:ios)

DEVELOPER_APP_ID_STAGING = ENV["DEVELOPER_APP_ID_STAGING"]
DEVELOPER_APP_IDENTIFIER_STAGING = ENV["DEVELOPER_APP_IDENTIFIER_STAGING"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

def delete_temp_keychain(name)
    delete_keychain(
      name: name
    ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
    create_keychain(
      name: name,
      password: password,
      unlock: false,
      timeout: true
    )
end

def ensure_temp_keychain(name, password)
    delete_temp_keychain(name)
    create_temp_keychain(name, password)
end

platform :ios do
    desc "Build a ice.ipa file"
    lane :buildStaging do
        build_app(scheme: "ice-staging",
        workspace: "ios/ice.xcworkspace",
        include_bitcode: true)
    end

    lane :buildProduction do
        build_app(scheme: "ice",
        workspace: "ios/ice.xcworkspace",
        include_bitcode: true)
    end

    desc "Push a new staging build to TestFlight"
    lane :buildStagingTestFlight do
        ruby_version("2.7.4")
        keychain_name = TEMP_KEYCHAIN_USER
        keychain_password = TEMP_KEYCHAIN_PASSWORD
        ensure_temp_keychain(keychain_name, keychain_password)

        api_key = app_store_connect_api_key(
            key_id: APPLE_KEY_ID,
            issuer_id: APPLE_ISSUER_ID,
            key_content: APPLE_KEY_CONTENT,            
            duration: 1200,            
            in_house: false
        )

        # increment_build_number(xcodeproj: "ice.xcodeproj")
        
        cocoapods(
            clean_install: true
        )
        
        match(
            type: 'appstore',
            app_identifier: "#{DEVELOPER_APP_IDENTIFIER_STAGING}",
            git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
            readonly: true,
            keychain_name: keychain_name,
            keychain_password: keychain_password,
            api_key: api_key
        )

        gym(
            configuration: "Release",
            workspace: "ice.xcworkspace",
            scheme: "ice-staging",
            export_method: "app-store",
            export_options: {
              provisioningProfiles: { 
                DEVELOPER_APP_ID_STAGING => PROVISIONING_PROFILE_SPECIFIER
              }
            }
          )

        pilot(
            apple_id: "#{DEVELOPER_APP_ID_STAGING}",
            app_identifier: "#{DEVELOPER_APP_IDENTIFIER_STAGING}",
            skip_waiting_for_build_processing: true,
            skip_submission: true,
            distribute_external: false,
            notify_external_testers: false,
            ipa: "./ice.ipa"
        )
    end

    desc "Push a new prod build to TestFlight"
    lane :buildProdTestFlight do
        # increment_build_number(xcodeproj: "ice.xcodeproj")
        match(type: "appstore")
        gym(workspace: "ice.xcworkspace", scheme: "ice")
        pilot(skip_submission: true, skip_waiting_for_build_processing: true,)
    end
end
