name: ice CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      - 'release/v*'
jobs:
  tests-and-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: main-repo
      - name: Checkout the target 'master' branch of 'mobile-app-secrets'
        uses: actions/checkout@v3
        with:
          repository: ice-blockchain/mobile-app-secrets
          ref: master
          token: ${{ secrets.ICE_CI_CD_BOT_GH_PAT }}
          path: mobile-app-secrets
          fetch-depth: 0
      - name: Run a multi-line script
        run: |
          mkdir $GITHUB_WORKSPACE/main-repo/configuration
          cp -a $GITHUB_WORKSPACE/mobile-app-secrets/configuration/. $GITHUB_WORKSPACE/main-repo/configuration/
          ls -l $GITHUB_WORKSPACE/main-repo/configuration
      - uses: actions/setup-node@master
      - name: Install npm dependencies
        run: |
          yarn

      - name: Check types
        run: |
          yarn check-types
      - name: Lint
        run: |
          yarn lint
      - name: Run tests
        run: |
          yarn test
